Repository sebasbogado/AdoptameNa-Frontend, pull requests merged in 2025-03, with the labels that each got.

#37 S-217 Fix Auth
  app/(pages)/(content)/profile/page.tsx
  app/(pages)/auth/layout.tsx
  app/(pages)/auth/login/page.tsx
  app/layout.tsx
  app/loading.tsx
  components/navbar.tsx
  components/petCard/cardText.tsx
  components/userHeader.tsx
  contexts/authContext.tsx
  package-lock.json
  package.json
  tailwind.config.ts
  types/auth.ts
  types/userProfile.ts
  types/users.ts
  utils/auth-client.ts
  utils/errors/AuthError.ts
Labels: bug

#38 S-218 not found page
  app/not-found.tsx
Labels: enhancement

#41 Update dashboard to connect to backend
  app/(pages)/(content)/dashboard/page.tsx
  components/Section.tsx
  types/post.ts
  utils/pets.http.ts
  utils/posts.http.ts
Labels: enhancement

#54 S-187 Editar perfil de usuario - Estado (En progreso)
  app/(pages)/(content)/adoption/page.tsx
  app/(pages)/(content)/dashboard/page.tsx
  app/(pages)/(content)/profile/page.tsx
  components/buttons/edit-button.tsx
  components/petCard/pet-card.tsx
  components/profile/detail-form.tsx
  components/section.tsx
  components/title.tsx
Labels: bug, enhancement

#56 FE - Realizar pantalla de lista de publicaciones de un usuario con acceso desde el perfil
  app/(pages)/(content)/profile/my-pets/[user-id]/page.tsx
  app/(pages)/(content)/profile/my-posts/[user-id]/page.tsx
  app/(pages)/(content)/profile/page.tsx
  components/footer.tsx
Labels: enhancement

#114 BUG - No aparece el boton de contactar en profile
  components/profile/dropdown-buttons.tsx
Labels: bug
